site_name: Marcos Luchetti
site_url: https://mluchetti.com
dev_addr: 127.0.0.1:7885
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/ml-icon.png
  favicon: assets/ml-icon.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: indigo


nav:
  - Home: index.md
  - About:
    - Resume: about/resume.md
  - Docs:
    - Setup: docs/index.md
    - EDR/SIEM:
      - CrowdStrike Falcon: docs/siem-edr/crowdstrike-falcon.md
      - IBM QRadar: docs/siem-edr/ibm-qradar.md
      - Wazuh: docs/siem-edr/wazuh.md
    - IAM:
      - Cisco Duo: docs/iam/cisco-duo.md
    - Remote Desktop:
      - RustDesk: docs/remote-desktop/rustdesk.md
    - Virtualization:
      - VirtualBox: docs/virtualization/virtualbox.md
    - Web Servers:
      - Caddy: docs/web-servers/caddy.md
      - Nginx Proxy Manager: docs/web-servers/npm.md
  - Blog:
    - blog/index.md
  - Tags: tags.md
  # - User Guide:
  #   - user-guide/admonitions.md
  #   - user-guide/content-tabs.md
  #   - user-guide/diagram-examples.md


plugins:
  - search
  - tags
  - blog
  - glightbox


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html


extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/marcos-luchetti/
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://github.com/mluchettii
    - icon: fontawesome/regular/envelope
      name: Email
      link: mailto:mluchettim@gmail.com

extra_css:
  - css/extra.css


copyright: Copyright &copy; 2025 Marcos Luchetti